### ISSUE TITLE
Notify when mounted folder mecomes visible

### ISSUE THREAD

**Issue by TtuxX** [rotdrop/nextcloud-app-files-archive#2]
Hi there @rotdrop ! :)

Let me first thank you for this AWESOME app !! This is so useful!! I cannot count the many times I downloaded an archive just to get the 1 file I was looking for inside it!
So, first, a big thank you for this incredible app (that should be integrated inside Nextcloud by default!).

Back to my issue, I was trying to mount an archive and didn't see it display right away.
When I tried to mount it again, your app notified me that archive was already mounted. But still, no new folder visible.
The folder became visible after some page reloads, maybe 40s-60s after having mounted it.
BTW, my NC config.php file has: 'filesystem_check_changes' => 1,

Would it be possible to make the mounted folder appear quicker, or to have a progress bar or notification, to know when the archive becomes visible and accesible in the user interface ?

Thank you very much in advance.

Kind regards

**Comment by rotdrop** [comment]
I cannot reproduce it in my development setup. But that is quite "customized" with some hacks in the NC core. I have to check wiith a vanilla setup ...

**Comment by rotdrop** [comment]
Although on one of my installations I had experienced the same problem I now cannot reproduce the error. Could you please verify that you still have this problem, i.e. try to mount again, maybe upload another archive?

Later I will try what happens with a new install (i.e. remove the app and install it anew). Maybe it only occur after a new installation. But then something is still wrong ...

**Comment by rotdrop** [comment]
This really seems to be a fresh installation problem. I occurred again on my vanilla NC 24 after de-installation and removing manually all remnants (database mount-points, storages).

After a new installation the problem was there again. I could be cured by manually running a file-scan via the "occ" command.

What surprises me most is that afterwards -- even with other archive files -- the mounts just appear immediately, without running a file-system scan again.  Anyhow, as the problem is reproducible, there will eventually be a solution.

In the mean, could you please verify that also on your setup:
- this is a first-time installation problem
- once the first mount showed up, all sub-sequent attempts (also with other archive files) just work

Thanks in advance! Best regards

Claus Heine

**Comment by TtuxX** [comment]
Thank you for your reactivity ! :)

My setup is:
- Version: 24.0.7
- Not a Nextcloud first time installation (migrated through years)
- A first time "Archive Inspector and Extractor" installation

I can observe that: 
- On the same archive: Once a folder has been mounted, I can unmount and remount it immediately, the process and files list works perfectly fine
- On a different archive in different folder: the results are inconsistent (sometimes it mounts and displays right away, sometimes the issue stays the same as initialy described)

**Comment by rotdrop** [comment]
This should be solved by the latest pre-release v1.0.3-alpha.

Can you please give it a try?

**Comment by TtuxX** [comment]
Thank you! :)
I tried using 3 different archives in different folder and mounting any .zip archive works immediately!
I still have the Zipper issue however.
