### ISSUE TITLE
Cannot change settings

### ISSUE THREAD

**Issue by LoxoSoftware** [rotdrop/nextcloud-app-files-archive#48]
When I try to increase the administrative size limit, the text in the input field resets to the default "4 GiB" and a toast shows up saying "Successfully set value for "archiveSizeLimit" to "4 GiB"".
To confirm this, the personal administrative size limit is still reported to be 4 GiB.
Is there a way to manually change this in the config files?

**Comment by rotdrop** [comment]
Could you please also report the version of the, and the NC version? Thanks.

Apart from this "formal" answer I think this is already solved in ebc2cd6

**Comment by LoxoSoftware** [comment]
> Could you please also report the version of the, and the NC version? Thanks.
> 
> Apart from this "formal" answer I think this is already solved in [ebc2cd6](https://github.com/rotdrop/nextcloud-app-files-archive/commit/ebc2cd6affe55e3dbdde602e6af2c7d23b0598fe)

I looked in to that commit and I updated to the latest pre-release version, but I still have the issue.
My Nextcloud version is 29.0.0

**Comment by LoxoSoftware** [comment]
![image](https://github.com/rotdrop/nextcloud-app-files-archive/assets/103667306/9f75a6cb-444a-4050-8604-52d21d0b1ced)
I moved the project folder to /var/www/nextcloud/apps and renamed it to "files_archive" but now it fails to enable it.

**Comment by rotdrop** [comment]
>  I moved the project folder to /var/www/nextcloud/apps and renamed it to "files_archive" but now it fails to enable it.

I do not quite understand. What do you mean by "project-folder"? What did you try to do?

**Comment by LoxoSoftware** [comment]
I was trying to install the app manually because the version in the store is outdated

**Comment by LoxoSoftware** [comment]
I figured out how to update it, now it works. I had to `chmod 777 files_archive -R` and that fixed it

**Comment by rotdrop** [comment]
Closing this as resolved.
